### ISSUE TITLE
Build 2 remaining Levels (3 & 4)

### ISSUE THREAD

**Issue by BananaPinguin** [Jan0707/flying-founders#11]
Input for Level Design from Robin

**Comment by svszot** [comment]
Level 3 liegt im Branch.
Leider ist das extrem Buggy.

Was aufgefallen ist:
- Die Balls sind nicht exakt 60x60px groß und pushen Objekte weg. Können wir das fixen?
- Konstruktionen sind mal wieder extrem instabil, wenn man sie stacked. Entweder ich hab irgendwo wieder einen Fehler drin, oder es liegt diesmal an den sehr dünnen Objekten.

**Comment by dckz74** [comment]
Done.
