### ISSUE TITLE
Choose Sounds and Implement at correct point in Game

### ISSUE THREAD

**Issue by BananaPinguin** [Jan0707/flying-founders#9]

**Comment by Jan0707** [comment]
For those looking to get started with this:

All sound is being controlled by this piece of the code: `./src/SoundSystem.ts`
There, all sounds should be preloaded (for performance and latency reasons) and then triggered via our event emitter in `./src/util/eventBus.ts`.

For an example on how to trigger a sound, [see here](https://github.com/Jan0707/flying-founders/blob/main/src/components/Level.vue#L30).
